<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{{ $header['report_title'] }}</title>

    <style>
        {!! file_get_contents(resource_path('views/Reports/CSS/Report.css')) !!}

        .report-content {
            width: 100%;
            margin: 0;
            padding: 0;
        }
        .data-table {
            margin-top: 10px;
        }

        .tab-section {
            width: 100%;
            margin: 12px 0 0 0;
            padding: 0;
            page-break-before: auto;
            page-break-after: auto;
            page-break-inside: auto;
        }

        .report-title {
            margin: 12px 0 6px 0;
            padding: 0;
            page-break-after: avoid;
        }

        .section {
            width: 100%;
            margin: 0 0 10px 0;
            padding: 0;
            page-break-before: auto;
            page-break-after: auto;
            page-break-inside: auto;
        }

        .section-heading {
            margin: 0;
            page-break-after: avoid;
        }

        .section-header-block {
            page-break-after: avoid;
        }

        table {
            width: 100%;
            page-break-before: auto;
            page-break-after: auto;
            page-break-inside: auto;
        }

        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }

        td,
        th {
            page-break-inside: avoid;
        }

        .field-value {
            word-wrap: break-word;
            overflow-wrap: break-word;
        }

        .array-value {
            margin: 0;
            padding: 0;
        }

        .array-item {
            margin: 0 0 2px 0;
            padding: 0;
        }
    </style>
</head>

<body>

    {{-- Header --}}
    <header>
        <div class="header-wrapper">

            <div class="header-left">
                <div class="logo-box">
                    <div class="logo-box-inner">
                        <img
                            src="{{ public_path('uploads/ReportLogo/shilpaimage.png') }}"
                            alt="Logo"
                        >
                    </div>
                </div>
            </div>

            <div class="header-center">
                <div class="company-name">
                    Shilpa Medicare Pvt Ltd
                </div>

                <div class="document-title">
                    {{ $header['report_title'] }}
                </div>

                <div class="document-subtitle">
                    Process Record Report
                </div>
            </div>

            <div class="header-right">
                <div class="logo-box">
                    <div class="logo-box-inner">
                        <img
                            src="{{ public_path('uploads/ReportLogo/vidyagxp_logo.png') }}"
                            alt="Logo"
                        >
                    </div>
                </div>
            </div>

        </div>
    </header>

    {{-- Footer --}}
    <footer>
        <div class="footer-wrapper">
            <table class="footer-table">
                <tr>
                    <td class="footer-left">
                        <div class="footer-company">
                            Shilpa Medicare Pvt Ltd
                        </div>

                        <div class="footer-meta">
                            {{ $header['report_title'] }}
                            &nbsp; | &nbsp;
                            Controlled Document
                        </div>
                    </td>

                    <td class="footer-right">
                        <div>
                            Generated By:
                            <strong>
                                {{ $footer['generated_by'] ?? 'System' }}
                            </strong>
                        </div>

                        <div class="footer-meta">
                            Generated On:
                            {{ $footer['generated_at'] ?? '-' }}
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </footer>

    {{-- Report Content --}}
    <div class="report-content">

        @foreach($tabs ?? [] as $tab)

            <div class="tab-section">

                {{-- Tab --}}
                <div class="report-title">
                    {{ $tab['tab_title'] ?? '-' }}
                </div>

                @foreach($tab['sections'] ?? [] as $section)

                    @if(!empty($section['fields']))

                        <div class="section">

                            {{-- Section --}}
                            <div class="section-heading section-header-block">
                                {{ $section['title'] ?? '-' }}
                            </div>

                            <table class="data-table">

                                <thead>
                                    <tr>
                                        <th>Field</th>
                                        <th>Value</th>
                                    </tr>
                                </thead>

                                <tbody>

                                    @foreach($section['fields'] as $field)

                                        <tr>

                                            <td class="field-name">
                                                {{ $field['label'] ?? '-' }}
                                            </td>

                                            <td class="field-value">

                                                @php
                                                    $value = $field['value'] ?? null;
                                                @endphp

                                                @if(is_array($value))

                                                    @if(isset($value['name']))
                                                        {{ $value['name'] }}

                                                    @elseif(count($value))

                                                        <div class="array-value">

                                                            @foreach($value as $item)

                                                                <div class="array-item">

                                                                    @if(is_array($item))

                                                                        @if(isset($item['name']))
                                                                            {{ $item['name'] }}
                                                                        @elseif(isset($item['file_name']))
                                                                            {{ $item['file_name'] }}
                                                                        @elseif(isset($item['original_name']))
                                                                            {{ $item['original_name'] }}
                                                                        @else
                                                                            {{ json_encode($item, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}
                                                                        @endif

                                                                    @else

                                                                        {{ $item }}

                                                                    @endif

                                                                </div>

                                                            @endforeach

                                                        </div>

                                                    @else
                                                        -
                                                    @endif

                                                @else

                                                    {{ $value !== null && $value !== '' ? $value : '-' }}

                                                @endif

                                            </td>

                                        </tr>

                                    @endforeach

                                </tbody>

                            </table>

                        </div>

                    @endif

                @endforeach

            </div>

        @endforeach

    </div>

</body>

</html>