<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    <title>{{ $header['report_title'] }}</title>

    <style>
        {!! file_get_contents(resource_path('views/Reports/CSS/Report.css')) !!}
    </style>
</head>

<body>

    {{-- header --}}
    <header>

        <div class="header-wrapper">

            {{-- LEFT LOGO --}}
            <div class="header-left">

                <div class="logo-box">
                    <div class="logo-box-inner">
                        COMPANY
                        <br>
                        LOGO
                    </div>
                </div>

            </div>


            {{-- CENTER --}}
            <div class="header-center">

                <div class="company-name">
                    Shilpa Medicare Pvt Ltd
                </div>

                <div class="document-title">
                    {{ $header['report_title'] }}
                </div>

                <div class="document-subtitle">
                    Process Record Report
                </div>

            </div>


            {{-- RIGHT LOGO --}}
            <div class="header-right">

                <div class="logo-box">
                    <div class="logo-box-inner">
                        COMPANY
                        <br>
                        LOGO
                    </div>
                </div>

            </div>

        </div>

    </header>


    {{-- =========================================================
    FOOTER
    ========================================================== --}}
    <footer>

        <div class="footer-wrapper">

            <table class="footer-table">

                <tr>

                    <td class="footer-left">

                        <div class="footer-company">
                            Shilpa Medicare Pvt Ltd
                        </div>

                        <div class="footer-meta">
                            {{ $header['report_title'] }}
                            &nbsp; | &nbsp;
                            Controlled Document
                        </div>

                    </td>

                    <td class="footer-right">

                        <div>
                            Generated By:
                            <strong>
                                {{ $footer['generated_by'] ?? 'System' }}
                            </strong>
                        </div>

                        <div class="footer-meta">
                            Generated On:
                            {{ $footer['generated_at'] }}
                        </div>

                    </td>

                </tr>

            </table>

        </div>

    </footer>


    {{-- =========================================================
    REPORT CONTENT
    ========================================================== --}}

    <div class="report-title">
        Process Record Details
    </div>


    {{-- =========================================================
    RECORD INFORMATION
    ========================================================== --}}

    <div class="section avoid-break">

        <div class="section-heading">
            Record Information
        </div>

        <table class="info-table">

            <tr>

                <td class="info-label">
                    Record ID
                </td>

                <td class="info-value">
                    {{ $record['record_id'] ?? '-' }}
                </td>

                <td class="info-label">
                    Process
                </td>

                <td class="info-value">
                    {{ $record['process'] ?? '-' }}
                </td>

            </tr>

            <tr>

                <td class="info-label">
                    Initiator
                </td>

                <td class="info-value">
                    {{ $record['initiator'] ?? '-' }}
                </td>

                <td class="info-label">
                    Department
                </td>

                <td class="info-value">
                    {{ $record['department'] ?? '-' }}
                </td>

            </tr>

            <tr>

                <td class="info-label">
                    Current Stage
                </td>

                <td class="info-value">
                    {{ $record['stage'] ?? '-' }}
                </td>

                <td class="info-label">
                    Initiation Date
                </td>

                <td class="info-value">
                    {{ $record['initiation_date'] ?? '-' }}
                </td>

            </tr>

            <tr>

                <td class="info-label">
                    Short Description
                </td>

                <td class="info-value" colspan="3">
                    {{ $record['short_description'] ?? '-' }}
                </td>

            </tr>

        </table>

    </div>


    {{-- =========================================================
    DYNAMIC PROCESS DATA
    ========================================================== --}}

    @if(!empty($fields))

        <div class="section">

            <div class="section-heading">
                Process Data
            </div>

            <table class="data-table">

                <thead>

                    <tr>
                        <th>
                            Field
                        </th>

                        <th>
                            Value
                        </th>
                    </tr>

                </thead>

                <tbody>

                    @foreach($fields as $key => $value)

                        <tr>

                            <td class="field-name">
                                {{ $key }}
                            </td>

                            <td class="field-value">

                                @if(is_array($value))

                                    <table class="nested-table">

                                        @foreach($value as $nestedKey => $nestedValue)

                                            <tr>

                                                <td class="nested-key">
                                                    {{ $nestedKey }}
                                                </td>

                                                <td>

                                                    @if(is_array($nestedValue))

                                                                        {{ json_encode(
                                                            $nestedValue,
                                                            JSON_UNESCAPED_UNICODE
                                                        ) }}

                                                    @else

                                                        {{ $nestedValue }}

                                                    @endif

                                                </td>

                                            </tr>

                                        @endforeach

                                    </table>

                                @else

                                    {{ $value ?: '-' }}

                                @endif

                            </td>

                        </tr>

                    @endforeach

                </tbody>

            </table>

        </div>

    @endif

</body>

</html>